### PR TITLE
Add shortcodes/ folder  as default

### PR DESCRIPTION
**Pull request by jmu**
Signed-off-by: Jiang <jmujmu@gmail.com>

shortcodes feature need shortcodes/* as assets to copy  when building project

https://bartholomew.fermyon.dev/shortcodes

### CODE REVIEW

**Review by vdice — COMMENTED** [review]
Hi @jmu, thank you very much for the PR!

I'm wondering if adding `shortcodes/*` to the spin.toml without a corresponding directory in source code might be slightly confusing.  What if we also add a `shortcodes` directory and perhaps an example shortcodes script?

Also, can we add a line mentioning this directory [along with the others in the README]( https://github.com/fermyon/bartholomew-site-template/blob/main/README.md#directory-structure)?

**Comment by jmu** [comment]
> Hi @jmu, thank you very much for the PR!
> 
> I'm wondering if adding `shortcodes/*` to the spin.toml without a corresponding directory in source code might be slightly confusing. What if we also add a `shortcodes` directory and perhaps an example shortcodes script?
> 
> Also, can we add a line mentioning this directory [along with the others in the README](https://github.com/fermyon/bartholomew-site-template/blob/main/README.md#directory-structure)?

Sure, I will push later

**Comment by vdice** [comment]
Thank you @jmu, this looks great.

One last ask: Can you please GPG-sign the commits on this PR?  (See https://developer.fermyon.com/cloud/contributing#8-commit-changes).  Please let me know if you have any questions on the process.

**Review by vdice — APPROVED** [review]
Thank you for your contribution!

**Pull request merged**
